---

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

stages:
  - check
  - test

variables:
  MAVEN_OPTS: >
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true

cache:
  paths:
    - babduino/.m2/repository

sast:
  stage: check

secret_detection:
  stage: check

verify:openjdk8:
  stage: test
  image: maven:3-openjdk-8-slim
  before_script:
    - 'cd babduino'
  script:
    - './mvnw $MAVEN_CLI_OPTS verify'
  only:
    - master

verify:openjdk11:
  stage: test
  image: maven:3-openjdk-11-slim
  before_script:
    - 'cd babduino'
  script:
    - './mvnw $MAVEN_CLI_OPTS verify'
  only:
    - master

verify:openjdk17:
  stage: test
  image: maven:3-openjdk-17-slim
  before_script:
    - 'cd babduino'
  script:
    - './mvnw $MAVEN_CLI_OPTS verify'
  only:
    - master

verify:openjdk18:
  stage: test
  image: maven:3-openjdk-18-slim
  before_script:
    - 'cd babduino'
  script:
    - './mvnw $MAVEN_CLI_OPTS verify'
  only:
    - master
